name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set up wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: Build and deploy
        run: |
          cargo update
          cd website
          wasm-pack build --release
          cd site
          npm install
          npm run build
          cd ../../
          cp -r website/site/dist ./

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BTHESIS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./www/dist
